#!/usr/bin/env bash
################################################################################
# autobuild - this script will rebuild a project (using make) whenever any
# dependencies change.
#
# Example:
#   $ cd wherever/project
#   $ autobuild
#
# Dependencies: inotify-tools
#     (https://github.com/rvoicilas/inotify-tools)
#
# Version 3
# Matthew Malensek <matt@malensek.net>
################################################################################

make

while true; do
    inotifywait -qq -e modify -r .
    if ! make -q; then
        make && echo -n "--> BUILD OK: " && date
    fi
done
