#!/usr/bin/env bash
################################################################################
# autobuild - this script will rebuild a project (using make) whenever any
# dependencies change.  Requires inotify-tools:
#   https://github.com/rvoicilas/inotify-tools
# Note: this probably doesn't scale well for large directory trees.
#
# Example:
#   cd wherever/project
#   autobuild
#
# Version 3
# Matthew Malensek <matt@malensek.net>
################################################################################

make

while true; do
    fswatch --one-event --latency=0.15 . &> /dev/null
    #inotifywait -qq -e modify -r .
    if ! make -q; then
        make && echo -n "--> BUILD OK: " && date
    fi
done
