#!/usr/bin/env bash
################################################################################
# gitbucket-update - downloads the latest version of GitBucket, an open-source
# GitHub clone (https://github.com/gitbucket/gitbucket). This script is likely
# to be a bit brittle, but to the best of my knowledge there is no "clean" way
# to retrieve the latest project release from GitHub.
#
# Version 1
# Matthew Malensek <matt@malensek.net>
################################################################################

checksum() {
    if command -v md5sum > /dev/null 2>&1; then
        md5sum "${1}" | awk '{ print $1 }'
    elif command -v md5 > /dev/null 2>&1; then
        md5 -q "${1}"
    else
        >&2 echo "Error: no md5 utility found!"
    fi
}

dir="${1}"
if [[ -z "${dir}" ]]; then
    echo "No download directory set. Using $(pwd)"
fi

# Grab the latest gitbucket version's URL. -L follows the redirect.
url=$(curl -s -L 'https://github.com/gitbucket/gitbucket/releases/latest' \
    | grep -o '"/gitbucket/gitbucket/releases/download/.*/gitbucket.war"' \
    | sed 's|"\(.*\)"|\1|g')

ver=$(sed 's|.*/\(.*\)/gitbucket.war|\1|g' <<< "${url}")

dl="${ver}.war"
if [[ -n "${dir}" ]]; then
    dl="${dir}/${dl}"
fi

if [[ -e "${dl}" ]]; then
    echo "File already exists: ${dl}"
    exit 1
fi

echo "Latest version: ${ver}"
echo "Downloading to: ${dl}"
curl -L "https://github.com/${url}" -o "${dl}"

echo "Verifying checksum..."
md5=$(curl -L "https://github.com/${url}.md5" | awk '{ print $1 }')
chk=$(checksum "${dl}")
if [[ "${md5}" != "${chk}" ]]; then
    echo "ERROR: Checksum mismatch: ${chk}"
else
    echo "Checksum ok: ${chk}"
fi
