#!/usr/bin/env bash
################################################################################
# gitbucket-update - downloads the latest version of GitBucket, an open-source
# GitHub clone (https://github.com/gitbucket/gitbucket).
#
# Version 1
# Matthew Malensek <matt@malensek.net>
################################################################################


dir="${1}"
if [[ -z "${dir}" ]]; then
    echo "No download directory set. Using $(pwd)"
fi

# Grab the latest gitbucket version's URL. -L follows the redirect.
url=$(curl -s -L 'https://github.com/gitbucket/gitbucket/releases/latest' \
    | grep -o '"/gitbucket/gitbucket/releases/download/.*/gitbucket.war"' \
    | sed 's|"\(.*\)"|\1|g')

ver=$(sed 's|.*/\(.*\)/gitbucket.war|\1|g' <<< "${url}")

echo "Latest version: ${ver}"
curl -L "https://github.com/${url}" -o "${ver}.war"
