#!/usr/bin/env bash

print_usage() {
cat <<EOM
Usage: $(basename ${0}) <image_dir>
EOM
}

dir=${1}

if [[ ! -d "${dir}" ]]; then
    print_usage
    exit 1
fi

echo "Reading image EXIF data..."
timelist=$(exiftool \
    -p '$dateTimeOriginal'$'\t''$directory/$filename' \
    -d '%s' \
    "${dir}" | sort -n)

counter=0
IFS=$'\n'
for img in $(echo "${timelist}"); do
    imgname=$(cut -f 2- <<< "${img}")
    imgdir=$(dirname "${imgname}")
    newname=$(printf "%s/%04d.%s" "${imgdir}" ${counter} "${imgname##*.}")
    mv -v "${imgname}" "${newname}"
    (( counter++ ))
done
