#!/usr/bin/env python
################################################################################
# pchng - a really simple tool to calculate the percent change between args.
# Yep, that's pretty much all there is to it.
#
# Version 1
# Matthew Malensek <matt@malensek.net>
################################################################################

def printchng(nums):
    from decimal import Decimal
    nums = map(Decimal, nums)
    p = None
    for n in nums:
        if p != None:
            change = (n - p) / p
            print("%g%%" % (change * 100))
        p = n

if __name__ == "__main__":
    import sys
    printchng(sys.argv[1:])
