#!/usr/bin/env python

def printchng(nums):
    from decimal import Decimal
    nums = map(Decimal, nums)
    p = None
    for n in nums:
        if p != None:
            change = (n - p) / p
            print("%g%%" % (change * 100))
        p = n

if __name__ == "__main__":
    import sys
    printchng(sys.argv[1:])
