#!/usr/bin/env python

def printchng(nums):
    from decimal import Decimal
    nums = map(Decimal, nums)
    p = None
    for n in nums:
        if p is None:
            p = n
            continue
        print((n - p) / p)
        p = n

if __name__ == "__main__":
    import sys
    printchng(sys.argv[1:])
