#!/usr/bin/env bash
################################################################################
# plexrefresh - tells a local Plex Media Server to scan for new items.
#
# Version 1
# Matthew Malensek <matt@malensek.net>
################################################################################

sections=$(curl 'http://localhost:32400/library/sections/' 2>/dev/null \
    | grep -o 'Location id=\"[0-9]*\"' \
    | sed 's/Location id=\"\([0-9]*\)\"/\1/g')

for section in ${sections}; do
    curl "http://localhost:32400/library/sections/${section}/refresh" &>/dev/null
done
