#!/usr/bin/env bash
################################################################################
# remove-audio - removes all audio tracks from a video file using ffmpeg.
#
# Dependencies: ffmpeg
################################################################################

ffmpeg -i "${1}" -vcodec copy -an "${2}"
print_usage() {
cat <<EOM
Usage: $(basename ${0}) input_file [output_file]
EOM
}
