#!/usr/bin/env bash
################################################################################
# remove-audio - removes all audio tracks from a video file using ffmpeg.
#
# Dependencies: ffmpeg
#
# Version 1
# Matthew Malensek <matt@malensek.net>
################################################################################

print_usage() {
cat <<EOM
Usage: $(basename ${0}) input_file [output_file]
EOM
}

input="${1}"
output="${2}"

if [[ -z "${input}" ]]; then
    print_usage
    exit 1
fi

if [[ -z "${output}" ]]; then
    output="${input%.*}-NOAUDIO.${input##*.}"
fi

echo "Input file: ${input}"
echo "Output file: ${output}"

ffmpeg -i "${input}" -vcodec copy -an "${output}"

echo "Audio removal complete: ${output}"
