#!/usr/bin/env bash
################################################################################
# tomp3 - converts audio files to VBR mp3s using ffmpeg.
#
# Dependencies: ffmpeg
#
# Version 1
# Matthew Malensek <matt@malensek.net>
################################################################################

quality=0
active_threads=0
max_threads=$( \
    (getconf _NPROCESSORS_ONLN || getconf NPROCESSORS_ONLN) 2> /dev/null)

print_usage() {
cat <<EOM
Usage: $(basename "${0}") [-t threads} [-V quality] files_to_convert

$(basename "${0}") converts audio files to VBR mp3s using ffmpeg. Options:
    * -t threads    Number of threads to use for conversion (default: ${max_threads})
    * -V quality    The LAME quality level to use (default: ${quality})
EOM
}

convert_audio() {
    from="${1}"
    ext="${from##*.}"
    to="${from[@]/%${ext}/mp3}"

    ffmpeg \
        -i "${from}" \
        -loglevel quiet \
        -codec:a libmp3lame -qscale:a "${quality}" \
        "${to}"

    echo "${from} -> ${to}"
    kill -s SIGUSR1 $$
}

thread_done() {
    (( active_threads-- ))
}
trap thread_done SIGUSR1

if ! ( which ffmpeg &> /dev/null ); then
    echo "Couldn't find ffmpeg!"
    exit 1
fi

while getopts "t:V:" flag; do
    case ${flag} in
        t) max_threads=${OPTARG} ;;
        V) quality=${OPTARG} ;;
        ?) print_usage; exit 1 ;;
    esac
done

shift $(( OPTIND - 1 ))

if [[ ${#} -lt 1 ]]; then
    print_usage
    exit 1
fi

for file in "${@}"; do
    convert_audio "${file}" &
    (( active_threads++ ))

    if [[ ${active_threads} -eq ${max_threads} ]]; then
        wait
    fi
done

until wait; do :; done
