#!/usr/bin/env bash

dir=${1}

if [[ ! -d "${1}" ]]; then
    echo "Not a directory: ${1}"
    exit 1
fi

cpus=$(getconf _NPROCESSORS_ONLN)

find "${dir}" | xargs -t -n1 -P"${cpus}" \
    mogrify -resize 1920x1080 -auto-orient
