#!/usr/bin/env bash
################################################################################
#

print_usage() {
cat <<EOM
Usage: $(basename ${0}) <image_dir>
EOM
}

dir=${1}

if [[ ! -d "${dir}" ]]; then
    print_usage
    exit 1
fi

cpus=$(getconf _NPROCESSORS_ONLN)

find "${dir}" | xargs -t -n1 -P"${cpus}" \
    mogrify -resize 1920x1080 -auto-orient
