#!/usr/bin/env bash
################################################################################
# yum-upchk - uses yum to check for updates and sends an email if there are any
# available.
#
# Version 1
# Matthew Malensek <matthew@malensek.net>
################################################################################

mail_to="root@somewhere"

# get the list of new updates, and remove any blank lines
update_list=$(yum --debuglevel=0 --errorlevel=0 check-update | sed '/^$/d')
num_updates=$(wc -l <<< "${update_list}")

subject="$num_updates updates available for $(hostname)"

if [[ $num_updates -gt 0 && $update_list != "" ]]; then
    echo "$update_list" | mail -s "$subject" $mail_to
fi
