#!/usr/bin/env bash
################################################################################
# zsnap - A very simple zfs snapshot management script.
#
# Version 1
# Matthew Malensek <matt@malensek.net>
################################################################################



if [[ ${#} -ne 1 ]]; then
    echo "Not enough arguments!"
    exit 1
fi

dataset="${1}"

snap_name=$(date '+%F')
snapshots=$(zfs list -H -t snapshot -o name -r "${dataset}" \
    | sed "s|${dataset}@||g")

for snapshot in ${snapshots}; do
    if [[ "${snap_name}" == "${snapshot}" ]]; then
        echo "Snapshot already exists; aborting"
        exit 1
    fi
done

zfs snapshot "${dataset}@${snap_name}"

